FROM openjdk:19

WORKDIR /app

COPY . .

COPY src/main/resources/application-baselimpa.properties.dev src/main/resources/application.properties

EXPOSE 8080

CMD ["./gradlew", "update"]

CMD ["./gradlew", "bootRun"]
