server.port=8080


scheduled.main=false
scheduled.busca.processos.conclusos=true
scheduled.devolve.origem=false
assinatura.digital.validar=true
#Intervalo em milisegundos
scheduled.sincronizar.processos=60000
#Intervalo em minutos
scheduled.intervalo.sincronizacao=-60

#Dev
spring.datasource.url=jdbc:postgresql://10.0.60.51:9023/meugabinete?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.platform=postgres
spring.datasource.connectionProperties=useUnicode=true;characterEncoding=utf-8;

#Back
GABINETE_HOST=

#ProxyPJE
URL_PJE_PG_REST=http://proxy-pje.apps.ocp-hml.intra.tjmg.gov.br

URL_PJE_SG_REST=

#OrgaoJulgador
lotacoes.url=http://orgao-julgador.apps.ocp-hml.intra.tjmg.gov.br

spring.messages.encoding=UTF-8
server.tomcat.uri-encoding=UTF-8
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false
spring.jpa.database=default
spring.jpa.hibernate.ddl-auto=none

spring.liquibase.enabled=true
spring.datasource.initialize=true
spring.liquibase.contexts=developer

modo.autenticacao=keycloak


keycloak.realm=pje
keycloak.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL:https://keycloak-mgab.apps.ocp-hml.intra.tjmg.gov.br/auth/realms/pje/protocol/openid-connect/token}
keycloak.client-id=pje-tjmg-1g
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:oNT3qcWC7D6UuTpi2jQpB6rwxNMUUOCT}
keycloak.redirect-uri=${KEYCLOAK_REDIRECT_URI:http://meu-gabinete-front.apps.ocp-hml.intra.tjmg.gov.br/login-keycloak}
keycloak.auth-server-url-logout=${KEYCLOAK_AUTH_SERVER_URL_LOGOUT:https://keycloak-mgab.apps.ocp-hml.intra.tjmg.gov.br/auth/realms/pje/protocol/openid-connect/logout}
keycloak.url-jwt=${KEYCLOAK_URL_JWT:https://keycloak-mgab.apps.ocp-hml.intra.tjmg.gov.br/auth/realms/pje}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_JWT_SET_URI:https://keycloak-mgab.apps.ocp-hml.intra.tjmg.gov.br/auth/realms/pje/protocol/openid-connect/certs}

# Max file size.
spring.servlet.multipart.max-file-size=10MB
# Max request size.
spring.servlet.multipart.max-request-size=20MB

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

Access-Control-Allow-Credentials:true

IA_ATIVADO=false
IA_HOST=http://tjrov-docker.tjro.net:8186/rest
IA_TIPO_CLASSIFICADOR=CLS_TIPO_MOVIMENTO_MAGISTRADO
IA_QTD_RAMIFICACOES=2
IA_QTD_PALAVRAS=4

KAFKA_HOST=http://10.0.60.51:9092
KAFKA_ENABLE_RUNNER=true

kafka.devolve.consumer=true

TGM_CODEX_ATIVADO=false

management.security.enabled=true

spring.zipkin.service.name=${TJRO_APPTAG:gabinete-back}
spring.zipkin.sender.type=web
spring.zipkin.baseUrl=http://zipkin:9411
spring.sleuth.sampler.percentage=0.0

URL_MICROSERVICE_METAS = http://localhost:4001

spring.cloud.stream.kafka.binder.brokers=${KAFKA_HOST:172.24.1.3:9092}
eureka.client.enabled=false

integracao.caixa.url=https://integracaocaixa.tjro.jus.br

# Modelos de Documentos
MODELO_DOCUMENTO_HOST=http://localhost:8091
TAG_VALIDA_EXPEDIENTE_CARTORIO:Validar Expediente Cartório|#8800df
CAIXA_VALIDA_EXPEDIENTE_CARTORIO:Validar Expediente Cartório

modelodocumento.back.host=http://modelo-documento-back.apps.okd4-hml.intra.tjmg.gov.br/
modelodocumento.front.host=http://pjetst-1.intra.tjmg.gov.br:9028


recursos.json=\
  {\
  "administrador":["Administrador(a)"],\
  "magistrado":["magistrado(a)","Administrador(a)","Escrivão(ã) Judicial","Usuário Justiça Restaurativa"],\
  "assessor":["Diretor de Secretaria","Assessor","Assessor TJRO"]\
  }

conta.centralizadora=\
  {\
   "banco": "104",\
   "agencia": "2848",\
   "operacao": "040.1",\
   "numeroConta": "01529904",\
   "digitoVerificador": "5",\
   "numeroProcesso":"00759114820108221111",\
   "idLegado":76605\
  }

tribunal=tjmg
nexus=http://nexus.intra.tjmg.gov.br/repository/public

URL_TPU=http://pjetst-1.intra.tjmg.gov.br:9033/api/v1

localizadores.url=http://localizador.apps.ocp-hml.intra.tjmg.gov.br

STORAGE_TYPE=jcr
STORAGE_URL=http://pjetst-1.intra.tjmg.gov.br:9001/storage/documents
STORAGE_USER=admin
STORAGE_SENHA=admin

assinatura.digital.validar=false

documento.url=http://10.0.60.51:9019/pje/seam/resource/rest/pje-legacy

URL_CORS=http://pjetst-1.intra.tjmg.gov.br:[*]
URL_CORS2=http://pjetst-1.intra.tjmg.gov.br:9040/*

verifica.tarefas.concluso=false
tarefas.concluso=Enviado para Meu Gabinete
scheduled.devolveParaIntegracaoAutomatico=true
