server.port=8090
# Apenas para teste
kafka.devolve.consumer=false

#Dev
spring.datasource.jdbcUrl=jdbc:postgresql://localhost:5432/windson
spring.datasource.username=MODULOGABINETE
spring.datasource.password=lh-modgab-1305
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.platform=postgres
spring.datasource.connectionProperties=useUnicode=true;characterEncoding=utf-8;

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
pedido.inclusao.pauta.mod-doc-template-id = 666
pedido.inclusao.pauta.template=<p><span data-tag="processo.numero">{{processo.numero}}</span></p>

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL95Dialect
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false
spring.jpa.database=default
spring.jpa.hibernate.ddl-auto=none

spring.messages.encoding=UTF-8
server.tomcat.uri-encoding=UTF-8
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# Max file size.
spring.servlet.multipart.max-file-size=10MB
# Max request size.
spring.servlet.multipart.max-request-size=20MB

#logging.level.org.hibernate.SQL=none
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=none

Access-Control-Allow-Credentials=true

GABINETE_HOST = http://localhost:8090
URL_PJE_PG_REST = http://localhost:8280
URL_PJE_SG_REST = http://localhost:8281

IA_ATIVADO=true
IA_HOST=http://tjrov-docker.tjro.net:8186/rest
IA_TIPO_CLASSIFICADOR=CLS_TIPO_MOVIMENTO_MAGISTRADO
IA_QTD_RAMIFICACOES=2
IA_QTD_PALAVRAS=4
IA_USER=gabiente
IA_PASSWORD=windson

URL_DOC_2_IMG=

KAFKA_HOST=172.24.1.3:9092
KAFKA_ENABLE_RUNNER = false

TGM_CODEX_ATIVADO = true
TAGS_CONEXUS_ATIVADO = true

lotacoes.url=https://pje.tjro.jus.br/pg/seam/resource/rest/pje-legacy
documento.url=https://pje.tjro.jus.br/pg/seam/resource/rest/pje-legacy

management.security.enabled=true

spring.zipkin.service.name=${TJRO_APPTAG:gabinete-back}
spring.zipkin.sender.type=web
spring.zipkin.baseUrl=http://zipkin:9411
spring.sleuth.sampler.percentage=1.0
URL_MICROSERVICE_METAS = http://localhost:4001


MINIO_HOST= http://172.17.0.2:9000
MINIO_BALDE= gabinete-homologacao
MINIO_ACCESS_KEY=WKPE7F6M979903RICDPJ
MINIO_SECRET_KEY=jNMbXYA5qYrwFksRZ4XFZ7vb3usoWu99OvkeR/cf
MINIO_SECURE=false


liquibase.enabled=false
tatus=

metrics_enable=true

STORAGE_URL=https://gabinete-storage.tjro.jus.br

URL_TPU=https://tpu.tjro.jus.br/api/v1

scheduled.main=false
scheduled.busca.processos.conclusos=false
scheduled.devolve.origem=false
assinatura.digital.validar=true

# Parans(jwt,keycloak,developer) Default is jwt
modo.autenticacao=jwt

#Configuração para o keycloak
keycloak.auth-server-url=http://localhost/auth
keycloak.realm=pje
keycloak.resource=hell
keycloak.public-client=false
keycloak.principal-attribute=preferred_username
keycloak.credentials.secret=64a695d2-d838-4d1c-a3d4-deec6e2d1364


hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds= 15000

logging.level.com.itextpdf.*=OFF

ALVARA_VALIDADE=30

modelodocumento.back.host=${MODELO_DOCUMENTO_HOST:http://localhost:8180}
modelodocumento.front.host=http://localhost:4201

zuul.routes.modelodocumento.path=/modelo-documentos/**
zuul.routes.modelodocumento.url=${modelodocumento.back.host}
