INSERT INTO MODULOGABINETE.USUARIO
(ID, ATIVO, MATRICULA, PERFIL_ACESSO, SENHA)
VALUES(1, 1, 'admin', 'ROLE_ADMINISTRADOR', '$2a$10$eAUQ7PQ0Idr5xUV3WsEUjO2fTSqsV4JZ/o5WUfx1yD7dYwHyXUrI.');

INSERT INTO MODULOGABINETE.USUARIO
(ID, ATIVO, MATRICULA, PERFIL_ACESSO, SENHA)
VALUES(2, 1, 'assessor', 'ROLE_ASSESSOR', '$2a$10$e030Sbmugt4p79.p9zkSt.T0DYuSNiq9Me9f3T5pmIVtA9ukj39la');

INSERT INTO MODULOGABINETE.USUARIO
(ID, ATIVO, MATRICULA, PERFIL_ACESSO, SENHA)
VALUES(3, 1, 'magistrado', 'ROLE_MAGISTRADO', '$2a$10$nsD81l01GJN1119PplsYwevkKVHEe42O7eH.E.V57or2iX4dTjEdW');

INSERT INTO MODULOGABINETE.ORGAOS_USUARIOS
(USUARIO_ID, ORGAOS_JULGADORES_ID)
VALUES(1, 3);

INSERT INTO MODULOGABINETE.ORGAOS_USUARIOS
(USUARIO_ID, ORGAOS_JULGADORES_ID)
VALUES(1, 4);

INSERT INTO MODULOGABINETE.ORGAOS_USUARIOS
(USUARIO_ID, ORGAOS_JULGADORES_ID)
VALUES(1, 5);

INSERT INTO MODULOGABINETE.ORGAOS_USUARIOS
(USUARIO_ID, ORGAOS_JULGADORES_ID)
VALUES(3, 5);

INSERT INTO MODULOGABINETE.ORGAOS_USUARIOS
(USUARIO_ID, ORGAOS_JULGADORES_ID)
VALUES(2, 4);

INSERT INTO MODULOGABINETE.ORGAOS_USUARIOS
(USUARIO_ID, ORGAOS_JULGADORES_ID)
VALUES(2, 3);
